# Generated by Django 5.0.3 on 2024-05-14 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0003_usuario_gmail_usuario_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base_questoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pergunta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_questoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ops', models.CharField(max_length=200)),
                ('voto', models.IntegerField(default=0)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cad_usuarios.base_questoes')),
            ],
        ),
    ]
